export const GET_BRAND_PRODUCTS = 'GET_BRAND_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const OPEN_MODAL = 'OPEN_MODAL'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const CHANGE_BRAND = 'CHANGE_BRAND'


